// Package oui resolves a MAC address to a vendor name using a bundled,
// embedded prefix table. No runtime network lookup, no filesystem dependency
// after process start.
//
// The bundled table lives in data.csv and is regenerated by tools/oui/refresh.sh
// from the IEEE registry. The CSV format is "PREFIX,VENDOR" with a single
// header line; PREFIX is uppercase, colon-separated, 24-bit (e.g. "B8:27:EB").
//
// @aitri-trace FR-033 US-033 AC-033-001 AC-033-002 TC-LD-004h TC-LD-004f TC-LD-004e
package oui

import (
	"bytes"
	_ "embed"
	"encoding/csv"
	"strings"
	"sync"
)

//go:embed data.csv
var bundledCSV []byte

const (
	unknownVendor = "Unknown"
	laaVendor     = "Locally administered"
)

var (
	loadOnce sync.Once
	table    map[string]string
)

func ensureLoaded() {
	loadOnce.Do(func() {
		table = parseCSV(bundledCSV)
	})
}

// Vendor returns the human-readable vendor name for a MAC.
//
// Behaviour:
//   - LAA bit set in the first byte → "Locally administered" (regardless of OUI).
//   - 24-bit OUI prefix found in the bundled table → that vendor.
//   - Otherwise → "Unknown".
//
// Inputs that do not parse as a MAC (too short, non-hex, etc.) return
// "Unknown" without error and without any side effect.
func Vendor(mac string) string {
	ensureLoaded()
	first, prefix, ok := normalize(mac)
	if !ok {
		return unknownVendor
	}
	// LAA: bit 1 (0x02) of the first octet → locally administered.
	if first&0x02 != 0 {
		return laaVendor
	}
	if v, ok := table[prefix]; ok {
		return v
	}
	return unknownVendor
}

// normalize accepts permissive MAC forms ("aa:bb:cc:dd:ee:ff", "AA-BB-CC-DD-EE-FF",
// "aabbccddeeff") and returns (firstByte, "AA:BB:CC", true). Anything else
// returns ok=false.
func normalize(mac string) (byte, string, bool) {
	cleaned := strings.NewReplacer(":", "", "-", "", ".", "", " ", "").Replace(mac)
	if len(cleaned) != 12 {
		return 0, "", false
	}
	for i := 0; i < 12; i++ {
		c := cleaned[i]
		switch {
		case c >= '0' && c <= '9':
		case c >= 'a' && c <= 'f':
		case c >= 'A' && c <= 'F':
		default:
			return 0, "", false
		}
	}
	upper := strings.ToUpper(cleaned)
	first := hexByte(upper[0], upper[1])
	prefix := upper[0:2] + ":" + upper[2:4] + ":" + upper[4:6]
	return first, prefix, true
}

func hexByte(hi, lo byte) byte {
	return hexNibble(hi)<<4 | hexNibble(lo)
}

func hexNibble(c byte) byte {
	switch {
	case c >= '0' && c <= '9':
		return c - '0'
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10
	}
	return 0
}

func parseCSV(raw []byte) map[string]string {
	out := map[string]string{}
	r := csv.NewReader(bytes.NewReader(raw))
	r.FieldsPerRecord = -1
	rows, err := r.ReadAll()
	if err != nil {
		return out
	}
	for i, row := range rows {
		if i == 0 || len(row) < 2 {
			continue
		}
		prefix := strings.ToUpper(strings.TrimSpace(row[0]))
		vendor := strings.TrimSpace(row[1])
		if prefix == "" || vendor == "" {
			continue
		}
		out[prefix] = vendor
	}
	return out
}
